favicon: /img/favicon.ico
# Change to your profile picture
avatar: /img/profile.png
# if author sets in hexo_config, this string doesn't work
author: 'Howard Yin'
author_bio: "Simon Fraser University"

since: 2020

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  Publications: /#Publications ||
  Blog: http://www.yindaheng98.top || fas fa-external-link-alt
menu_right:
  About: https://github.com/yindaheng98 ||

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.png

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Github: https://github.com/yindaheng98 || fab fa-github
  Google Scholar: https://scholar.google.com/citations?user=XblbcSYAAAAJ&hl=zh-CN&oi=sra || fas fa-graduation-cap
  ORCID: https://orcid.org/0000-0002-9431-4240 || fab fa-orcid
  Email: mailto:yindaheng98@gmail.com || fas fa-envelope

# CV download link
cv_dl:
  enable: true
  dir: /attaches/CV_DahengYin.pdf
  description: My CV in PDF.
# 中文CV下载链接
cv_dl_zh:
  enable: true
  dir: /attaches/简历_尹达恒.pdf
  description: 我的中文简历PDF.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js